-- Exam configuration table
-- Stores full ExamConfig as JSONB, keeps last 10 versions
create table if not exists public.question_bank (
  id bigint generated by default as identity primary key,
  data jsonb not null,
  updated_at timestamptz not null default now()
);

alter table public.question_bank enable row level security;

-- Allow public read (student exams fetch config)
create policy "Public can read question_bank"
  on public.question_bank
  for select
  to anon, authenticated
  using (true);

-- Allow public insert (teacher saves config)
create policy "Public can insert question_bank"
  on public.question_bank
  for insert
  to anon, authenticated
  with check (true);

-- Allow public delete (auto-cleanup keeps last 10 versions)
create policy "Public can delete question_bank"
  on public.question_bank
  for delete
  to anon, authenticated
  using (true);

create index if not exists question_bank_updated_at_idx
  on public.question_bank (updated_at desc);
